modLoader="javafml"
loaderVersion="[${forge_major_ver},)"
license="MIT License"
issueTrackerURL="https://github.com/aksource/ChainDestruction/issues"
displayURL="https://github.com/aksource/ChainDestruction"
#logoFile="examplemod.png" #optional
credits="Thanks for Minecraft Forge developers"
authors="A.K."
[[mods]]
modId="chaindestruction"
version="[${file.jarVersion}]"
displayName="ChainDestruction"
updateJSONURL="https://raw.githubusercontent.com/aksource/ChainDestruction/master/update.json"
description='''
This mod allow you to destroy a block cluster at once when you using a tool to mine.
You can register blocks and tools in game.
'''

[[dependencies.chaindestruction]]
modId = "ak_lib"
mandatory = true
versionRange = "[1.0.3,)"
ordering = "NONE"
side = "BOTH"
