modLoader="javafml" #mandatory
loaderVersion="[41,)" #mandatory (24 is current forge version)
license="MIT License"
issueTrackerURL="https://github.com/aksource/ChainDestruction/issues" #optional
displayURL="https://github.com/aksource/ChainDestruction" #optional
#logoFile="examplemod.png" #optional
credits="Thanks for Minecraft Forge developers" #optional
authors="A.K." #optional
[[mods]] #mandatory
modId="chaindestruction" #mandatory
version="1.19-1.6.6.4" #mandatory
displayName="ChainDestruction" #mandatory
updateJSONURL="https://raw.githubusercontent.com/aksource/ChainDestruction/master/update.json" #optional
description='''
This mod allow you to destroy a block cluster at once when you using a tool to mine.
You can register blocks and tools in game.
'''

[[dependencies.chaindestruction]]
modId = "ak_lib"
mandatory = true
versionRange = "[1.0.3,)"
ordering = "NONE"
side = "BOTH"
