name: announce

on:
  release:
    types: [released]

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Tweet
        uses: snow-actions/tweet@v1.4.0
        env:
          CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          CONSUMER_API_SECRET_KEY: ${{ secrets.TWITTER_CONSUMER_API_SECRET_KEY }}
          ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        with:
          status: |
            連鎖破壊MOD更新 ${{ github.event.release.name }}
            ${{ github.event.release.html_url }}
